# Type hints for ploptions.py

from typing import List, Dict, Optional, Any, Union
from datetime import datetime

class AxisOptions:
    """Per-axis options for adding lines and customization."""
    _vertical_lines: List[Dict[str, Any]]
    _horizontal_lines: List[Dict[str, Any]]
    
    def __init__(self) -> None: ...
    
    def add_vertical_line(
        self,
        time: Union[str, datetime],
        color: str = 'black',
        style: str = '--',
        width: float = 1.0,
        label: Optional[str] = None
    ) -> None: ...
    
    def add_horizontal_line(
        self,
        value: float,
        color: str = 'black',
        style: str = '--',
        width: float = 1.0,
        label: Optional[str] = None
    ) -> None: ...
    
    def clear_vertical_lines(self) -> None: ...
    def clear_horizontal_lines(self) -> None: ...
    def clear_all_lines(self) -> None: ...
    
    @property
    def vertical_lines(self) -> List[Dict[str, Any]]: ...
    
    @property
    def horizontal_lines(self) -> List[Dict[str, Any]]: ...

class PlotbotOptions:
    """Global options for controlling plotbot figure behavior."""
    return_figure: bool
    display_figure: bool
    axes: Dict[int, AxisOptions]
    
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def _get_axis_options(self, axis_number: int) -> AxisOptions: ...
    
    # Per-axis property accessors
    @property
    def ax1(self) -> AxisOptions: ...
    @property
    def ax2(self) -> AxisOptions: ...
    @property
    def ax3(self) -> AxisOptions: ...
    @property
    def ax4(self) -> AxisOptions: ...
    @property
    def ax5(self) -> AxisOptions: ...
    @property
    def ax6(self) -> AxisOptions: ...
    @property
    def ax7(self) -> AxisOptions: ...
    @property
    def ax8(self) -> AxisOptions: ...
    @property
    def ax9(self) -> AxisOptions: ...
    @property
    def ax10(self) -> AxisOptions: ...
    @property
    def ax11(self) -> AxisOptions: ...
    @property
    def ax12(self) -> AxisOptions: ...
    @property
    def ax13(self) -> AxisOptions: ...
    @property
    def ax14(self) -> AxisOptions: ...
    @property
    def ax15(self) -> AxisOptions: ...
    @property
    def ax16(self) -> AxisOptions: ...
    @property
    def ax17(self) -> AxisOptions: ...
    @property
    def ax18(self) -> AxisOptions: ...
    @property
    def ax19(self) -> AxisOptions: ...
    @property
    def ax20(self) -> AxisOptions: ...
    @property
    def ax21(self) -> AxisOptions: ...
    @property
    def ax22(self) -> AxisOptions: ...
    @property
    def ax23(self) -> AxisOptions: ...
    @property
    def ax24(self) -> AxisOptions: ...
    @property
    def ax25(self) -> AxisOptions: ...
    
    def __repr__(self) -> str: ...

# Global instance
ploptions: PlotbotOptions

